import * as Sentry from "@sentry/nextjs";

// Derived from the installed SDK rather than naming an exported type, so a
// Sentry major that reshuffles its type exports can't break this file.
type SentryOptions = NonNullable<Parameters<typeof Sentry.init>[0]>;
type BeforeSend = NonNullable<SentryOptions["beforeSend"]>;

// Server-side: read from runtime-config.json (generated by server-wrapper.js) with process.env fallback
let SENTRY_DSN = process.env.NEXT_PUBLIC_LEARNHOUSE_SENTRY_DSN;
let LEARNHOUSE_ENV = process.env.NEXT_PUBLIC_LEARNHOUSE_ENV || "dev";

try {
  const fs = require("fs");
  const path = require("path");
  const possiblePaths = [
    path.join(process.cwd(), "runtime-config.json"),
    path.join(__dirname || process.cwd(), "runtime-config.json"),
    path.join(__dirname || process.cwd(), "..", "runtime-config.json"),
  ];
  for (const configPath of possiblePaths) {
    try {
      if (fs.existsSync(configPath)) {
        const rc = JSON.parse(fs.readFileSync(configPath, "utf8"));
        SENTRY_DSN = rc.NEXT_PUBLIC_LEARNHOUSE_SENTRY_DSN || SENTRY_DSN;
        LEARNHOUSE_ENV = rc.NEXT_PUBLIC_LEARNHOUSE_ENV || LEARNHOUSE_ENV;
        break;
      }
    } catch {
      // Continue to next path
    }
  }
} catch {
  // Fallback to process.env
}

/**
 * Exported so tests/sentry-filters.test.mjs can exercise every rule directly.
 * Each one cost a triage pass to identify; a silent deletion would refill the
 * project with the same noise, and only a test makes that fail loudly.
 *
 * Not filterable here, and deliberately so: Sentry's own `ai_detected_*`
 * detectors (Blocking Operation, Failed HTTP Operation) synthesise issues from
 * spans server-side rather than from events we send, so no beforeSend rule can
 * reach them. Turn those detectors down in the Sentry project's settings — a
 * single slow cold-start render, or a 500 on Next's internal /_error route
 * while an already-reported error was being rendered, is not a defect here.
 * They must NOT be closed as resolved-by-fix: nothing in this repo changes the
 * spans or the threshold, so a resolved issue simply reopens on the next cold
 * start. Archive/ignore them in Sentry instead.
 */
export const beforeSendServer: BeforeSend = (event, hint) => {
  const msg =
    (hint?.originalException as Error)?.message ??
    event?.exception?.values?.[0]?.value ??
    "";

  if (msg.includes("Failed to find Server Action")) return null;
  if (msg.includes("Organization not found")) return null;
  if (msg.includes("Organization has no config")) return null;
  // Next.js internal: raised when a client/bot sends a malformed
  // Next-Router-State-Tree header. Handled by Next (falls back to full
  // render) — not actionable from app code.
  if (msg.includes("router state header was sent but could not be parsed")) return null;
  // Next raises this when the HTTP response socket closes before the RSC stream
  // finishes flushing: the visitor navigated away, hit stop, or a crawler
  // dropped the connection mid-render. Every frame is Next's own compiled
  // runtime, there is no application frame, and the render is already complete
  // or already abandoned by the time it fires. Worth revisiting only if the
  // volume climbs out of proportion to traffic — that would be a symptom of
  // slow SSR giving users time to bail, not a stream bug in itself.
  if (msg.includes("The destination stream closed early")) return null;

  return event;
};

if (SENTRY_DSN) {
  Sentry.init({
    dsn: SENTRY_DSN,
    environment: LEARNHOUSE_ENV,
    sendDefaultPii: true,
    enableLogs: true,
    tracesSampleRate: LEARNHOUSE_ENV === "dev" ? 1.0 : 0.1,
    beforeSend: beforeSendServer,
  });
}
