import * as Sentry from "@sentry/nextjs";

// Server-side: read from runtime-config.json (generated by server-wrapper.js) with process.env fallback
let SENTRY_DSN = process.env.NEXT_PUBLIC_LEARNHOUSE_SENTRY_DSN;
let LEARNHOUSE_ENV = process.env.NEXT_PUBLIC_LEARNHOUSE_ENV || "dev";

try {
  const fs = require("fs");
  const path = require("path");
  const possiblePaths = [
    path.join(process.cwd(), "runtime-config.json"),
    path.join(__dirname || process.cwd(), "runtime-config.json"),
    path.join(__dirname || process.cwd(), "..", "runtime-config.json"),
  ];
  for (const configPath of possiblePaths) {
    try {
      if (fs.existsSync(configPath)) {
        const rc = JSON.parse(fs.readFileSync(configPath, "utf8"));
        SENTRY_DSN = rc.NEXT_PUBLIC_LEARNHOUSE_SENTRY_DSN || SENTRY_DSN;
        LEARNHOUSE_ENV = rc.NEXT_PUBLIC_LEARNHOUSE_ENV || LEARNHOUSE_ENV;
        break;
      }
    } catch {
      // Continue to next path
    }
  }
} catch {
  // Fallback to process.env
}

if (SENTRY_DSN) {
  Sentry.init({
    dsn: SENTRY_DSN,
    environment: LEARNHOUSE_ENV,
    sendDefaultPii: true,
    enableLogs: true,
    tracesSampleRate: LEARNHOUSE_ENV === "dev" ? 1.0 : 0.5,
  });
}
