import crypto from 'node:crypto'
import type { SetupConfig } from '../types.js'

function generateSecret(): string {
  return crypto.randomBytes(32).toString('base64')
}

export function generateEnvFile(config: SetupConfig): string {
  const protocol = config.useHttps ? 'https' : 'http'
  const portSuffix = (config.useHttps && config.httpPort === 443) || (!config.useHttps && config.httpPort === 80)
    ? ''
    : `:${config.httpPort}`
  const baseUrl = `${protocol}://${config.domain}${portSuffix}`
  const domainWithPort = `${config.domain}${portSuffix}`

  const topDomain = config.domain === 'localhost'
    ? 'localhost'
    : config.domain.split('.').slice(-2).join('.')

  const cookieDomain = config.domain === 'localhost'
    ? '.localhost'
    : `.${topDomain}`

  const nextAuthSecret = generateSecret()
  const jwtSecret = generateSecret()

  const lines: string[] = [
    '# LearnHouse Environment Variables',
    '# Generated by LearnHouse CLI',
    '',
    '# =============================================================================',
    '# Domain & Hosting Configuration',
    '# =============================================================================',
    '',
    `LEARNHOUSE_DOMAIN=${domainWithPort}`,
    `HTTP_PORT=${config.httpPort}`,
    '',
    '# =============================================================================',
    '# Frontend Environment Variables (NEXT_PUBLIC_*)',
    '# =============================================================================',
    '',
    `NEXT_PUBLIC_LEARNHOUSE_API_URL=${baseUrl}/api/v1/`,
    `NEXT_PUBLIC_LEARNHOUSE_BACKEND_URL=${baseUrl}/`,
    `NEXT_PUBLIC_LEARNHOUSE_DOMAIN=${domainWithPort}`,
    `NEXT_PUBLIC_LEARNHOUSE_TOP_DOMAIN=${topDomain}`,
    'NEXT_PUBLIC_LEARNHOUSE_MULTI_ORG=False',
    'NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG=default',
    `NEXT_PUBLIC_LEARNHOUSE_HTTPS=${config.useHttps ? 'True' : 'False'}`,
  ]

  if (config.unsplashEnabled && config.unsplashAccessKey) {
    lines.push(`NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=${config.unsplashAccessKey}`)
  }

  lines.push(
    '',
    '# =============================================================================',
    '# NextAuth Configuration',
    '# =============================================================================',
    '',
    `NEXTAUTH_URL=${baseUrl}`,
    `NEXTAUTH_SECRET=${nextAuthSecret}`,
  )

  if (config.googleOAuthEnabled && config.googleClientId && config.googleClientSecret) {
    lines.push(
      `LEARNHOUSE_GOOGLE_CLIENT_ID=${config.googleClientId}`,
      `LEARNHOUSE_GOOGLE_CLIENT_SECRET=${config.googleClientSecret}`,
    )
  }

  lines.push(
    '',
    '# =============================================================================',
    '# Backend Configuration',
    '# =============================================================================',
    '',
    `LEARNHOUSE_SQL_CONNECTION_STRING=${config.useExternalDb
      ? config.externalDbConnectionString
      : `postgresql://learnhouse:${config.dbPassword}@db:5432/learnhouse`}`,
    `LEARNHOUSE_REDIS_CONNECTION_STRING=${config.useExternalRedis
      ? config.externalRedisConnectionString
      : 'redis://redis:6379/learnhouse'}`,
    `LEARNHOUSE_COOKIE_DOMAIN=${cookieDomain}`,
    'LEARNHOUSE_PORT=9000',
    '',
    '# =============================================================================',
    '# Security',
    '# =============================================================================',
    '',
    `LEARNHOUSE_AUTH_JWT_SECRET_KEY=${jwtSecret}`,
    `LEARNHOUSE_INITIAL_ADMIN_EMAIL=${config.adminEmail}`,
    `LEARNHOUSE_INITIAL_ADMIN_PASSWORD=${config.adminPassword}`,
    '',
    '# =============================================================================',
    '# General Settings',
    '# =============================================================================',
    '',
    'LEARNHOUSE_DEVELOPMENT_MODE=False',
    'LEARNHOUSE_LOGFIRE_ENABLED=False',
    'LEARNHOUSE_OSS=True',
    'NEXT_PUBLIC_LEARNHOUSE_OSS=True',
  )

  if (config.aiEnabled && config.geminiApiKey) {
    lines.push(
      '',
      '# =============================================================================',
      '# AI Configuration',
      '# =============================================================================',
      '',
      `LEARNHOUSE_GEMINI_API_KEY=${config.geminiApiKey}`,
      'LEARNHOUSE_IS_AI_ENABLED=True',
    )
  } else {
    lines.push(
      '',
      '# =============================================================================',
      '# AI Configuration',
      '# =============================================================================',
      '',
      'LEARNHOUSE_IS_AI_ENABLED=False',
    )
  }

  if (config.emailEnabled && config.resendApiKey) {
    lines.push(
      '',
      '# =============================================================================',
      '# Email Configuration',
      '# =============================================================================',
      '',
      `LEARNHOUSE_RESEND_API_KEY=${config.resendApiKey}`,
      `LEARNHOUSE_SYSTEM_EMAIL_ADDRESS=${config.systemEmailAddress || `noreply@${config.domain}`}`,
    )
  }

  if (config.s3Enabled && config.s3BucketName) {
    lines.push(
      '',
      '# =============================================================================',
      '# Content Delivery',
      '# =============================================================================',
      '',
      'LEARNHOUSE_CONTENT_DELIVERY_TYPE=s3api',
      `LEARNHOUSE_S3_API_BUCKET_NAME=${config.s3BucketName}`,
    )
    if (config.s3EndpointUrl) {
      lines.push(`LEARNHOUSE_S3_API_ENDPOINT_URL=${config.s3EndpointUrl}`)
    }
  } else {
    lines.push(
      '',
      '# =============================================================================',
      '# Content Delivery',
      '# =============================================================================',
      '',
      'LEARNHOUSE_CONTENT_DELIVERY_TYPE=filesystem',
    )
  }

  if (!config.useExternalDb) {
    lines.push(
      '',
      '# =============================================================================',
      '# Database Configuration',
      '# =============================================================================',
      '',
      'POSTGRES_USER=learnhouse',
      `POSTGRES_PASSWORD=${config.dbPassword}`,
      'POSTGRES_DB=learnhouse',
      '',
    )
  } else {
    lines.push('')
  }

  return lines.join('\n')
}
