import {
  Buildings,
  Palette,
  Storefront,
  Compass,
  Robot,
  Globe,
  Lightning,
  Key,
  Lock,
  Sliders,
  ChartBar,
  DotsThree,
} from '@phosphor-icons/react'
import type { SearchMeta } from '@/lib/dashboard-search/types'

export const searchMetas: SearchMeta[] = [
  {
    id: 'dash.org.general',
    titleKey: 'dashboard.organization.settings.tabs.general',
    descriptionKey: 'dashboard.search.entries.org_general.description',
    keywordsKey: 'dashboard.search.entries.org_general.keywords',
    icon: Buildings,
    href: '/dash/org/settings/general',
    group: 'settings',
  },
  {
    id: 'dash.org.branding',
    titleKey: 'dashboard.organization.settings.tabs.branding',
    descriptionKey: 'dashboard.search.entries.org_branding.description',
    keywordsKey: 'dashboard.search.entries.org_branding.keywords',
    icon: Palette,
    href: '/dash/org/settings/branding',
    group: 'settings',
  },
  {
    id: 'dash.org.features',
    titleKey: 'dashboard.organization.settings.tabs.features',
    descriptionKey: 'dashboard.search.entries.org_features.description',
    keywordsKey: 'dashboard.search.entries.org_features.keywords',
    icon: Sliders,
    href: '/dash/org/settings/features',
    group: 'settings',
  },
  {
    id: 'dash.org.landing',
    titleKey: 'dashboard.organization.settings.tabs.landing',
    descriptionKey: 'dashboard.search.entries.org_landing.description',
    keywordsKey: 'dashboard.search.entries.org_landing.keywords',
    icon: Storefront,
    href: '/dash/org/settings/landing',
    group: 'settings',
  },
  {
    id: 'dash.org.seo',
    titleKey: 'dashboard.organization.settings.tabs.seo',
    descriptionKey: 'dashboard.search.entries.org_seo.description',
    keywordsKey: 'dashboard.search.entries.org_seo.keywords',
    icon: Compass,
    href: '/dash/org/settings/seo',
    group: 'settings',
  },
  {
    id: 'dash.org.ai',
    titleKey: 'dashboard.organization.settings.tabs.ai',
    descriptionKey: 'dashboard.search.entries.org_ai.description',
    keywordsKey: 'dashboard.search.entries.org_ai.keywords',
    icon: Robot,
    href: '/dash/org/settings/ai',
    group: 'settings',
  },
  {
    id: 'dash.org.domains',
    titleKey: 'dashboard.organization.settings.tabs.domains',
    descriptionKey: 'dashboard.search.entries.org_domains.description',
    keywordsKey: 'dashboard.search.entries.org_domains.keywords',
    icon: Globe,
    href: '/dash/org/settings/domains',
    group: 'settings',
  },
  {
    id: 'dash.org.automations',
    titleKey: 'dashboard.organization.settings.tabs.automations',
    descriptionKey: 'dashboard.search.entries.org_automations.description',
    keywordsKey: 'dashboard.search.entries.org_automations.keywords',
    icon: Lightning,
    href: '/dash/org/settings/automations',
    group: 'settings',
  },
  {
    id: 'dash.org.api',
    titleKey: 'dashboard.organization.settings.tabs.api',
    descriptionKey: 'dashboard.search.entries.org_api.description',
    keywordsKey: 'dashboard.search.entries.org_api.keywords',
    icon: Key,
    href: '/dash/org/settings/api',
    group: 'settings',
  },
  {
    id: 'dash.org.sso',
    titleKey: 'dashboard.organization.settings.tabs.sso',
    descriptionKey: 'dashboard.search.entries.org_sso.description',
    keywordsKey: 'dashboard.search.entries.org_sso.keywords',
    icon: Lock,
    href: '/dash/org/settings/sso',
    group: 'settings',
  },
  {
    id: 'dash.org.usage',
    titleKey: 'dashboard.organization.settings.tabs.usage',
    descriptionKey: 'dashboard.search.entries.org_billing.description',
    keywordsKey: 'dashboard.search.entries.org_billing.keywords',
    icon: ChartBar,
    href: '/dash/org/settings/usage',
    group: 'settings',
  },
  {
    id: 'dash.org.other',
    titleKey: 'dashboard.organization.settings.tabs.other',
    descriptionKey: 'dashboard.search.entries.org_other.description',
    keywordsKey: 'dashboard.search.entries.org_other.keywords',
    icon: DotsThree,
    href: '/dash/org/settings/other',
    group: 'settings',
  },
]
