name: Team
description: You are someone from the team
labels: ["team"]
body:
  - type: markdown
    attributes:
      value: 
  - type: checkboxes
    attributes:
      label: Is this issue planned ?
      options:
        - label: Planned
          
