name: Team
description: You are someone from the team
labels: ["team"]
body:
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
