"""Organizations new model

Revision ID: 87a621284ae4
Revises: 0314ec7791e1
Create Date: 2024-12-17 22:51:50.998443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '87a621284ae4'
down_revision: Union[str, None] = '0314ec7791e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('about', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('organization', sa.Column('socials', sa.JSON(), nullable=True))
    op.add_column('organization', sa.Column('links', sa.JSON(), nullable=True))
    op.add_column('organization', sa.Column('previews', sa.JSON(), nullable=True))
    op.add_column('organization', sa.Column('explore', sa.Boolean(), nullable=True))
    op.add_column('organization', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'label')
    op.drop_column('organization', 'explore')
    op.drop_column('organization', 'previews')
    op.drop_column('organization', 'links')
    op.drop_column('organization', 'socials')
    op.drop_column('organization', 'about')
    # ### end Alembic commands ###
