from pydantic import BaseModel, field_validator
from typing import Optional, List, Dict, Literal


class AttachmentData(BaseModel):
    """Attachment data sent with a message"""
    type: Literal['image', 'video', 'file', 'youtube']
    name: str
    url: Optional[str] = None  # For YouTube links
    content_base64: Optional[str] = None  # For uploaded files
    mime_type: Optional[str] = None  # MIME type for uploaded files


class ActivityPlan(BaseModel):
    """Plan for a single activity within a chapter"""
    name: str
    type: str = "TYPE_DYNAMIC"  # Default activity type
    description: str
    suggested_blocks: List[str] = []  # e.g., ['heading1', 'paragraph', 'quiz']


class ChapterPlan(BaseModel):
    """Plan for a single chapter within a course"""
    name: str
    description: str
    activities: List[ActivityPlan] = []


class CoursePlan(BaseModel):
    """Complete course plan generated by AI"""
    name: str
    description: str
    learnings: str = ""
    tags: list[str] = []
    chapters: List[ChapterPlan] = []

    @field_validator("tags", mode="before")
    @classmethod
    def _coerce_tags(cls, v):
        # The prompt asks for a JSON array, but a stray generation (or an
        # older client) may still send a delimited string. Accept either and
        # normalize to a clean list, so tags never 422 the finalize call. The
        # storage separator (pipe) is finalize's job, not the model's.
        if v is None:
            return []
        if isinstance(v, str):
            v = v.replace("|", ",").split(",")
        return [t.strip() for t in v if isinstance(t, str) and t.strip()]


class CoursePlanningMessage(BaseModel):
    """Single message in the conversation history"""
    role: str  # "user" or "model"
    content: str


class CoursePlanningSessionData(BaseModel):
    """Session data stored in Redis"""
    session_uuid: str
    org_id: int
    language: str = "en"  # Language code for content generation
    planning_iteration_count: int = 0
    max_planning_iterations: int = 10
    activity_iteration_counts: Dict[str, int] = {}  # activity_uuid -> iteration count
    max_activity_iterations: int = 6
    message_history: List[CoursePlanningMessage] = []
    current_plan: Optional[CoursePlan] = None
    course_id: Optional[int] = None  # Set after finalization


class StartCoursePlanningSession(BaseModel):
    """Request to start a new course planning session"""
    org_id: int
    prompt: str  # Initial course description from user
    language: str = "en"  # Language code for content generation (e.g., "en", "fr", "de")
    attachments: Optional[List[AttachmentData]] = None  # Context files/links


class SendCoursePlanningMessage(BaseModel):
    """Request to continue planning with a new message"""
    session_uuid: str
    message: str
    current_plan: Optional[CoursePlan] = None  # User-modified plan to iterate on
    attachments: Optional[List[AttachmentData]] = None  # Context files/links


class FinalizeCoursePlanRequest(BaseModel):
    """Request to finalize the plan and create course structure"""
    session_uuid: str
    plan: CoursePlan  # The final plan to create in the database


class GenerateActivityContentRequest(BaseModel):
    """Request to generate content for a specific activity"""
    session_uuid: str
    activity_uuid: str
    activity_name: str
    activity_description: str
    chapter_name: str
    course_name: str
    course_description: str
    prompt: Optional[str] = None  # Additional instructions for content generation


class SaveActivityContentRequest(BaseModel):
    """Request to save AI-generated content to an activity"""
    activity_uuid: str
    content: Dict  # ProseMirror JSON content


class CoursePlanningSessionResponse(BaseModel):
    """Response when getting session state"""
    session_uuid: str
    planning_iteration_count: int
    max_planning_iterations: int
    current_plan: Optional[CoursePlan]
    message_history: List[CoursePlanningMessage]
    course_id: Optional[int] = None


class FinalizeCoursePlanResponse(BaseModel):
    """Response after finalizing the course plan"""
    course_uuid: str
    course_id: int
    chapters: List[Dict]  # List of created chapters with their activities
