from pydantic import BaseModel, Field, field_validator
from typing import Optional, List, Dict, Literal

from src.services.ai.schemas.limits import (
    AI_CONTEXT_MAX_CHARS,
    AI_LABEL_MAX_CHARS,
    AI_MESSAGE_MAX_CHARS,
)

# Attachments are decoded into memory and sent inline to the model. 15MB
# decoded stays under the provider's ~20MB inline request ceiling.
MAX_ATTACHMENTS = 10
MAX_ATTACHMENT_TOTAL_BYTES = 15 * 1024 * 1024


class AttachmentData(BaseModel):
    """Attachment data sent with a message"""
    type: Literal['image', 'video', 'file', 'youtube']
    name: str = Field(max_length=AI_LABEL_MAX_CHARS)
    url: Optional[str] = Field(default=None, max_length=2048)  # For YouTube links
    content_base64: Optional[str] = None  # For uploaded files
    mime_type: Optional[str] = Field(default=None, max_length=255)  # MIME type for uploaded files


def _check_attachments(v: Optional[List[AttachmentData]]) -> Optional[List[AttachmentData]]:
    """Cap attachment count and total decoded size (base64 is ~4/3 the bytes)."""
    if not v:
        return v
    if len(v) > MAX_ATTACHMENTS:
        raise ValueError(f"At most {MAX_ATTACHMENTS} attachments are allowed")
    total = sum(len(a.content_base64 or "") for a in v) * 3 // 4
    if total > MAX_ATTACHMENT_TOTAL_BYTES:
        raise ValueError(
            f"Attachments exceed {MAX_ATTACHMENT_TOTAL_BYTES // (1024 * 1024)}MB in total"
        )
    return v


class ActivityPlan(BaseModel):
    """Plan for a single activity within a chapter"""
    name: str
    type: str = "TYPE_DYNAMIC"  # Default activity type
    description: str
    suggested_blocks: List[str] = []  # e.g., ['heading1', 'paragraph', 'quiz']


class ChapterPlan(BaseModel):
    """Plan for a single chapter within a course"""
    name: str
    description: str
    activities: List[ActivityPlan] = []


class CoursePlan(BaseModel):
    """Complete course plan generated by AI"""
    name: str
    description: str
    learnings: str = ""
    tags: list[str] = []
    chapters: List[ChapterPlan] = []

    @field_validator("tags", mode="before")
    @classmethod
    def _coerce_tags(cls, v):
        # The prompt asks for a JSON array, but a stray generation (or an
        # older client) may still send a delimited string. Accept either and
        # normalize to a clean list, so tags never 422 the finalize call. The
        # storage separator (pipe) is finalize's job, not the model's.
        if v is None:
            return []
        if isinstance(v, str):
            v = v.replace("|", ",").split(",")
        return [t.strip() for t in v if isinstance(t, str) and t.strip()]


class CoursePlanningMessage(BaseModel):
    """Single message in the conversation history"""
    role: str  # "user" or "model"
    content: str


class CoursePlanningSessionData(BaseModel):
    """Session data stored in Redis"""
    session_uuid: str
    org_id: int
    language: str = "en"  # Language code for content generation
    planning_iteration_count: int = 0
    max_planning_iterations: int = 10
    activity_iteration_counts: Dict[str, int] = {}  # activity_uuid -> iteration count
    max_activity_iterations: int = 6
    message_history: List[CoursePlanningMessage] = []
    current_plan: Optional[CoursePlan] = None
    course_id: Optional[int] = None  # Set after finalization
    user_id: Optional[int] = None  # Who started the session; None for sessions from before this field


class StartCoursePlanningSession(BaseModel):
    """Request to start a new course planning session"""
    org_id: int
    prompt: str = Field(max_length=AI_MESSAGE_MAX_CHARS)  # Initial course description from user
    language: str = Field(default="en", max_length=AI_LABEL_MAX_CHARS)  # Language code for content generation (e.g., "en", "fr", "de")
    attachments: Optional[List[AttachmentData]] = None  # Context files/links

    _validate_attachments = field_validator("attachments")(_check_attachments)


class SendCoursePlanningMessage(BaseModel):
    """Request to continue planning with a new message"""
    session_uuid: str
    message: str = Field(max_length=AI_MESSAGE_MAX_CHARS)
    current_plan: Optional[CoursePlan] = None  # User-modified plan to iterate on
    attachments: Optional[List[AttachmentData]] = None  # Context files/links

    _validate_attachments = field_validator("attachments")(_check_attachments)


class FinalizeCoursePlanRequest(BaseModel):
    """Request to finalize the plan and create course structure"""
    session_uuid: str
    plan: CoursePlan  # The final plan to create in the database


class GenerateActivityContentRequest(BaseModel):
    """Request to generate content for a specific activity"""
    session_uuid: str
    activity_uuid: str
    activity_name: str = Field(max_length=AI_LABEL_MAX_CHARS)
    activity_description: str = Field(max_length=AI_CONTEXT_MAX_CHARS)
    chapter_name: str = Field(max_length=AI_LABEL_MAX_CHARS)
    course_name: str = Field(max_length=AI_LABEL_MAX_CHARS)
    course_description: str = Field(max_length=AI_CONTEXT_MAX_CHARS)
    prompt: Optional[str] = Field(default=None, max_length=AI_MESSAGE_MAX_CHARS)  # Additional instructions for content generation


class SaveActivityContentRequest(BaseModel):
    """Request to save AI-generated content to an activity"""
    activity_uuid: str
    content: Dict  # ProseMirror JSON content


class CoursePlanningSessionResponse(BaseModel):
    """Response when getting session state"""
    session_uuid: str
    planning_iteration_count: int
    max_planning_iterations: int
    current_plan: Optional[CoursePlan]
    message_history: List[CoursePlanningMessage]
    course_id: Optional[int] = None


class FinalizeCoursePlanResponse(BaseModel):
    """Response after finalizing the course plan"""
    course_uuid: str
    course_id: int
    chapters: List[Dict]  # List of created chapters with their activities
